### ISSUE TITLE
Various thoughts following first session

### ISSUE THREAD

**Issue by katharinebreeze** [moj-analytical-services/writing_functions_in_r#42]
* The code on the slides seemed a bit faint from the other side of the room which may have made it hard to read
* I had a good question from someone about passing arguments into purr::modify_at() which it could be worth including/adding a note about (kind of going beyond the scope of the course so maybe just a note)
* We covered it anyway today, but I wondered whether we need a dedicated slide explain the difference between if(){} else(){} statements and ifelse() and case_when() and when to use each
* We could add an appendix example which has a function which uses ‘…’ to cope with an unknown number of arguments (e.g. our own version of sum() ) (or wait to see if we’re ever asked about this again/add a link for people to find out more)
* Might want to also cover `&` vs `&&` and also mention or is `|` (or say how to bring up help page)
* Wondering if there are any easy ways to improve attendee participation, e.g. asking people to share their solutions to examples or brain storm what a function is or something?

**Comment by chloepugh** [comment]
Here are a few of my thoughts:

> The code on the slides seemed a bit faint from the other side of the room which may have made it hard to read

Definitely worth trying to address. Not sure how easy it'll be with the restricted formatting but should be attempted.

> I had a good question from someone about passing arguments into purr::modify_at() which it could be worth including/adding a note about (kind of going beyond the scope of the course so maybe just a note)

Yeah I think if we can write a short note that could be added where `modify_if()` is first used.

> We covered it anyway today, but I wondered whether we need a dedicated slide explain the difference between if(){} else(){} statements and ifelse() and case_when() and when to use each

Since this isn't the focus of the course, and might be difficult to explain in a short note, I think this might be best added to the appendix with a note in the main content referring to the appendix.

> We could add an appendix example which has a function which uses ‘…’ to cope with an unknown number of arguments (e.g. our own version of sum() ) (or wait to see if we’re ever asked about this again/add a link for people to find out more)

Yes sounds good

> Might want to also cover & vs && and also mention or is | (or say how to bring up help page)

Again could be something for the appendix, and referred to in the main content, just to avoid distracting from the functions-related stuff.

**Comment by katharinebreeze** [comment]
Also for future reference just listing the questions asked in the [Coding in Analysis and Research Survey](https://www.smartsurvey.co.uk/s/OOZ32/) about use of functions -

9. For each of the following please answer to what extent you agree:
* I write my code as functions to avoid repetition
* I write my code as functions to make my code easier to read
* I write my code as functions to make my code easier to change
* I write my code as functions to make my code easier to test

I think we've already covered the first three and the fourth is out of scope but I like the way they set it out & it could be interesting to take a look at the results of the survey too.

**Comment by katharinebreeze** [comment]
Just to flag there is now some feedback on airtable -
https://airtable.com/shr3D0i9Rvu0op20R/tbll9EWeTBcjHgHSy?blocks=hide
(you can filter to just "writing functions in R").

Very positive about the material but there seem to be two prevailing themes that -
* The session could do with being a bit longer/we went through the material quite quickly, especially the second half
* We need to make it clear people need to be confident in the intro R material when we advertise the session

I suggest we stop thinking about this now until sometime after Christmas, apart from to update the R training group on how it went. (:

**Comment by aidanmews** [comment]
Katharine/Chloe - I have worked through the material myself (although I haven't tried the exercises) - well done on an excellent addition! A few thoughts (some possibly for the medium/long rather than short term) in addition to those above:
1) May be helpful to explain return(result) the first time it appears even if very briefly and without providing a full explanation.
2) Add a 'the' in 'Hint: if you want your function to work with the pipe operator %>%, make sure object you want to pipe (usually a dataframe) is the first argument for your function'.
3) Example 5: presumably the '## Error in x%%2: non-numeric argument to binary operator' relates to the odd_or_even(x = "a")
4) Exercise 2.2 covers a really important issue so does it work merely as an exercise, not least given the later guidance that 'Where possible you should write your function so it can take a vector as
an input and apply the transformation to each element.'? Maybe at the very least could link to a good example where using case_when etc. instead of if else etc. so people have a useful template?
5) The following seems a little impenetrable (could do with a very brief explanation?): x <- stringr::str_replace(x, "^[:digit:]{1,2}[:blank:]*:[:blank:]*|^[:digit:]{1,2}[:blank:]", "")
6) The tolower(x) could also be commented upon in the one line explanation accompanying:
 x <- ifelse(tolower(x) %in% values_to_change, not_known_phrase, x)
7) 'The R ecosystem is full of high quality packages designed to solve all kinds of problems - it’s generally best to make sure that a function doesn’t already exist before writing your own.' Any tips practically about where to look and for how long before making your own? Also do we need some guidance about how to write functions in MoJ so others can find them?   
8) 'A key measure of a good function (or any piece of code) is how easy it is for someone else to understand, use and modify it. The best way to test this is to get your code reviewed by someone else.' We need to do something about people being able to find a code reviewer when no-one available in their teams - I'll see if we can take up as part of the trello board work. 
9) Are there any disadvantages with 'The easiest way to store your functions is just to create a folder in your project called “functions” and save your functions there.'?

**Comment by katharinebreeze** [comment]
Thanks Aidan, these all look like good points.

Some of the omissions are things we explained in the training but, if we want the material to be standalone, they should be in the text as well!

I will go through this in more detail next time we review the material but have a couple of follow questions while it's fresh in your mind -

> 3. Example 5: presumably the '## Error in x%%2: non-numeric argument to binary operator' relates to the odd_or_even(x = "a")

Yep - are you saying this needs explaining in the text?

> Also do we need some guidance about how to write functions in MoJ so others can find them?

I think this might be something to signpost as it's probably something for people to think about after they're comfortable writing functions. I'd imagine the guidance would be -

* To make repos viewable to others in MoJ where possible (probably fits with coding standards?)
* Follow a consistent structure (probably fits with coding standards?)
* Add functions to packages such as `asdrap` (probably fits with packages training but could signpost here?)

> Are there any disadvantages with 'The easiest way to store your functions is just to create a folder in your project called “functions” and save your functions there.'?

I'd say the disadvantages are basically the advantages of using packages - so maybe you could suggest what we should be saying here! In the packages section (which comes straight after) we currently say:

> * It means you (and others) can access your functions from different projects
> * There are certain requirements for making R packages that enforce good practice, such as including documentation

**Comment by chloepugh** [comment]
> Are there any disadvantages with 'The easiest way to store your functions is just to create a folder in your project called “functions” and save your functions there.'?

For the example in this course we use a script called `functions.R` in the main folder, rather than a separate "functions" folder. So we could mention that as an option as well (where there aren't many functions to store).

**Comment by katharinebreeze** [comment]
Just adding a new issue we experienced this time (10/3/20):

* someone didn't have s3tools installed by default, even though according to the AP guidance it should be. The guidance for installing it is [here.](https://user-guidance.services.alpha.mojanalytics.xyz/amazon-s3.html#amazon-s3-console)
