### ISSUE TITLE
Go through material and look for and amend any content which is missing for someone reading material as a stand alone document

### ISSUE THREAD

**Issue by katharinebreeze** [moj-analytical-services/writing_functions_in_r#63]
This was raised by Aidan in issue #42.

**Comment by markrangan** [comment]
Me and @katharinebreeze have agreed to keep slide 50 (titled Summarising data).

Considering whether to keep generalise_names functions or replace it?

I'll look at slides about NSE and see if we need to replace the group_by_at function from dplyr.

Might remove the section on "Plotting data" due to its ggplot theme (and possible exercise 6)? Material on changing theme would be less relevant than changing variables.

Katharine will have a look at the janitor package to see if we should use that instead of the stringr functions written in the generalise_names function.

I'll be moving slides 61 and 62 to the appendix.

@chloepugh how does this sound?

**Comment by katharinebreeze** [comment]
Thanks Mark.

@chloepugh just to give some context we did a quick review of the material to find any sections which we could be candidates for removing/reducing in length or moving to an appendix. We only had time to look through the real world examples section so there may be other areas which could be cut back as well.

R.e. generalise_names I think we've discussed previously the regex is a bit impenetrable for anyone not familiar with it - I know I have seen an existing function *somewhere* which does something very similar so we could use that instead to shorten than section.

R.e. plotting data we discussed the theme changing example might fit better in the ggplot training, but that the changing variables is quite a good example for writing functions, so we could cut this down as well.

Then with slides 61 and 62 I think that's the section we've never actually had time to present!

**Comment by chloepugh** [comment]
Yep that sounds good! And yeah the janitor package has some quite helpful functions in it. Only slight downside is that it isn't pre-installed on the AP RStudio, so participants would need to install it themselves.

**Comment by katharinebreeze** [comment]
I think the function I was thinking of is `janitor::clean_names()`.

Yeah the fact it's not installed by default could cause additional problems for anyone who is struggling to follow the training. Feels like something they should be able to cope with though!
